@echo off
del "Compiled.trigger"
for /r "C:\Users\Michael\Documents\GitHub\SCRcrusaderkings\Triggers" %%a in (*.txt) do type "%%a" >>"Compiled.trigger"

fart Compiled.trigger "Income" "Protoss Photon Cannon"
fart Compiled.trigger "Mobilization Stage" "Flag" 
fart Compiled.trigger "Duchy Index ID" "Data Disc" 
fart Compiled.trigger "Manual Levy Switch" "Scanner Sweep" 
fart Compiled.trigger "Diplomacy Unit" "Protoss Forge" 
fart Compiled.trigger "Unit Spawn Stage" "Protoss Unused type   2" 
fart Compiled.trigger "Upgrade Buffer 1 (unit spawn)" "Protoss Unused type   1" 
fart Compiled.trigger "Pay Resources Switch" "Protoss Gateway" 
fart Compiled.trigger "Permanent Manpower" "Mineral Chunk (Type 1)" 
fart Compiled.trigger "Effective Manpower" "Mineral Field (Type 1)" 
fart Compiled.trigger "Manpower Regen" "Mineral Chunk (Type 2)" 
fart Compiled.trigger "Siege Calculations (Detect Player)" "Tank Turret type   2" 
fart Compiled.trigger "County/Duchy Upgrade Switch" "Kakaru (Twilight)" 
fart Compiled.trigger "Explosion Effect" "Terran Battlecruiser"
fart Compiled.trigger "Siege Timer" "Terran Starport"
fart Compiled.trigger "Duchy Unit" "Protoss Cybernetics Core"
fart Compiled.trigger "Raise Local Levy" "Tom Kazansky (Wraith)"
fart Compiled.trigger "Disable Levy" "Terran SCV"
fart Compiled.trigger "Enable Levy" "Zerg Queen"
fart Compiled.trigger "Duchy Demobilization Tracker" "Terran Science Vessel"
fart Compiled.trigger "Religion" "Protoss Marker"
fart Compiled.trigger "Raised Army Size" "Zerg Beacon"
fart Compiled.trigger "Upgrade Buffer 2 (restore HP)" "Zerg Marker"
fart Compiled.trigger "HolyWar" "Zerg Drone"